### ISSUE TITLE
About the datasets used in PCIC2021

### ISSUE THREAD

**Issue by zhjcp** [huawei-noah/trustworthyAI#101]
Thank you for sharing these three datasets from PCIC2021. I tested some methods on these three datasets, but found that the results were not satisfactory. I suspect that the difficulty of these three datasets may be relatively high, so I would like to test and compare on other datasets of the same type. I noticed that there are a total of 30 datasets in PCIC2021. Would it be possible for you to also make the remaining 27 datasets and their corresponding ground truth dags open source?

**Comment by zhjcp** [comment]
Also, I wonder if all 30 datasets are collected from real-world environment ? Or some of them are simulated ?

**Comment by shaido987** [comment]
Hello, 

I think my colleague already has answered your email but adding an answer here too for completeness. The three datasets from the PCIC2021 competition that has already been open-sourced are the only ones collected in a real-world environment. The other datasets are synthetic ones.

**Comment by zhjcp** [comment]
Ok, thank you !
