### ISSUE TITLE
Strength of causal links?

### ISSUE THREAD

**Issue by aaorsi** [huawei-noah/trustworthyAI#102]
Hi! Excellent library! have you considered including a measure of causal strength, like parameter learning for bayesian networks but applied to these DAGs? What would you suggest to estimate that?

**Comment by shaido987** [comment]
Hello,

There are some algorithms that can already return a weighted structure as a result of how the DAG is computed. You can take a look at LiNGAM family of algorithms. gCastle provides ICA-based LiNGAM and DirectLiNGAM, but there are more extensions, you can take a look here for an overview: https://sites.google.com/view/sshimizu06/lingam

**Comment by aaorsi** [comment]
Fantastic, thanks a lot!
