### ISSUE TITLE
Question about the timestamp unit of the dataset

### ISSUE THREAD

**Issue by zhjcp** [huawei-noah/trustworthyAI#104]
Hello,

I would like to ask what is the time stamp unit of the PCIC2021 dataset ? seconds, milliseconds, microseconds, or nanoseconds ？

**Comment by shaido987** [comment]
Hello,

The timestamps are all in seconds for the 3 PCIC2021 datasets.

**Comment by zhjcp** [comment]
In that case, it seems like each of the three datasets spans over hundreds of hours, which is a very very very long time interval, right ?

**Comment by zhjcp** [comment]
Specifically, the maximum timestamp of the first dataset is 20774867, and an interval of 20774867 timestamps is equivalent to 5000+ hours, right (it seems to span over too many hours) ?

**Comment by shaido987** [comment]
Yes, it should be correct. These are datasets from real telecom networks and the alarms are related to the failures in the network. These types of failures are not too frequent, hence, the dataset stretches over a long time. You can also see the [other telecom dataset we open-sourced](https://github.com/huawei-noah/trustworthyAI/tree/master/datasets) (although with a different format) that is not related to the PCIC competition which spans around half a year as well.

**Comment by zhjcp** [comment]
Ok, thank you again for your response.
