### ISSUE TITLE
About the topology information of the first of the three PCIC21 datasets

### ISSUE THREAD

**Issue by zhjcp** [huawei-noah/trustworthyAI#107]

**Comment by zhjcp** [comment]
Hello, I noticed that the first dataset of PCIC2021 contains device_id records but lacks the topology information (Topology.npy). I would like to know if the first dataset originally did not include Topology.npy? Or did you retain this part of the data and not make it public? If possible, could you make this portion of the data public?

**Comment by zhjcp** [comment]
ok, thank you for the response.

**Comment by shaido987** [comment]
Happy to help!
