### ISSUE TITLE
Different outputs for web GUI and python implementation 

### ISSUE THREAD

**Issue by marti5ini** [huawei-noah/trustworthyAI#112]
Hello, I have noticed a notable difference between the results obtained when running an algorithm by importing the library using pip, and the results obtained when utilizing the web GUI application. Is it possible to delve into the underlying factors contributing to this difference?

**Comment by shaido987** [comment]
Hello, could you give an example of what the differences are? Using stochastic algorithms can give differences in the results, so ensure the seed is the same. Also, is there any difference running with the latest code from GitHub (as there are some minor changes since version 1.0.3 which is installed using pip)?

**Comment by marti5ini** [comment]
Hello, thank you for your response. I have verified the version, and the web app and the library are operating on version 1.0.3. I couldn't find any newer version available.
I am attaching the two graph versions obtained using the default parameters of the PC and the data used for the generation.
![generated_graph__GUI](https://github.com/huawei-noah/trustworthyAI/assets/26304232/f53ffd91-6623-4d96-a7dc-08b9791c1561)
![generated_graph__python](https://github.com/huawei-noah/trustworthyAI/assets/26304232/883a6e3d-8da9-4f07-a366-f9eb5ae4e2c4)
[data.csv](https://github.com/huawei-noah/trustworthyAI/files/11915189/data.csv)

**Comment by shaido987** [comment]
This was a bug in how the edges are saved in the web GUI (and the shown result there was therefore incorrect). I have pushed a fix that should solve the problem, you can try with the latest code version and check so that it works. Thanks for reporting the issue!
