### ISSUE TITLE
Enhancement: Update _simulate_linear_sem() function to support list of SEM types

### ISSUE THREAD

**Issue by VineetMalik14** [huawei-noah/trustworthyAI#117]
Currently, the _simulate_linear_sem() function in simulator.py only accepts a single string to denote the SEM type for all n noise variables. This limits the function's flexibility as it assumes all variables have the same SEM type.

To allow for more complex simulations and model specifications, I have updated simulate_linear_SEM on my branch to accept either a single string or a list of SEM types. If a single string is provided, the function generates a list of size n, repeating the SEM type for all variables. If a list is provided, the function validates that the list is of length n and that all elements are strings, each denoting the SEM type for a particular variable.

This enhancement allows users to specify different SEM types for each variable, offering more flexibility and precision in defining the structure of their SEMs.

I would be happy to create a pull request with these changes for review. Please let me know if this aligns with the project roadmap and if it would be a good time to raise a PR.

**Comment by shaido987** [comment]
Hello, 

We would be happy to accept a PR with this added functionality! Please feel free to open a PR whenever it is convenient.

**Comment by VineetMalik14** [comment]
Thanks. I have raised the PR, please review: https://github.com/huawei-noah/trustworthyAI/pull/118
