### ISSUE TITLE
Problem with task list

### ISSUE THREAD

**Issue by margasm99** [huawei-noah/trustworthyAI#127]
I was using the GUI implementation and evaluating a DAG after causal discovery and the "evaluate" button simply stopped working. Afterward, I returned to my task list and all my tasks disappeared and the task list shows "no data" and when I try to create a new task using the button "Add task" it does not work, it doesn't open the usual window so I can choose between causal discovery or data generation.

**Comment by shaido987** [comment]
Did you accidentally close the command window where you were running the Flask server? Could you try restarting and see if the problem persists or if you can replicate it again? If it's still present after restarting, could you include a screenshot to show what it looks like?

**Comment by margasm99** [comment]
The command window is still open running the Flask server, I will include a screenshot of the task list and of the command window. I am not sure how this happened since I was doing an evaluation that I had done before, when trying to calculate the F1 value it didn't work and when I went back, saw all the tasks disappear.

<img width="959" alt="Screenshot 2023-08-17 155853" src="https://github.com/huawei-noah/trustworthyAI/assets/102806376/534c8d96-d569-4904-af90-cb106ff7e2c0">
<img width="936" alt="Screenshot 2023-08-17 155946" src="https://github.com/huawei-noah/trustworthyAI/assets/102806376/efd3c067-b2fa-4a44-bb77-5b3820e5d0bd">

**Comment by margasm99** [comment]
i had to redownload the files and it solved this, I think it happened while computing F1 and dividing by zero
