### ISSUE TITLE
Making a plt 

### ISSUE THREAD

**Issue by margasm99** [huawei-noah/trustworthyAI#132]
I want a graph to show me the value of the bic score on the y-axis and the different parent configurations in x-axis, however I am having a problem using the plt.show() while also using the GUI implementation. How could I solve this?

**Comment by shaido987** [comment]
Hello,

To do something like this, it would be more convenient to write the Python code instead. You could loop over all your configurations, compute the scores, and then plot. It's not clear to me how you are trying to integrate the plotting into the GUI but it seems to me to be a much more convoluted approach. One way would be to manually record the scores and create the plot afterward.
