### ISSUE TITLE
Question about castle.algorithms.RL using GPU

### ISSUE THREAD

**Issue by Ethan-Chen-plus** [huawei-noah/trustworthyAI#133]
![image](https://github.com/huawei-noah/trustworthyAI/assets/84905965/971beef4-43e9-4624-ac2d-1b1e9b4db616)
When I use castle.algorithms.RL to fit my data, I use device `GPU`, but by using `nvidia-smi` to check, there is no running progress on gpus.

**Comment by shaido987** [comment]
Hello,

could you try using `RL(device_type='gpu')` (in lowercase) to see if it works? You can also try to specify the device ID with the `device_ids` parameter, e.g., setting `device_ids=0`.

**Comment by Ethan-Chen-plus** [comment]
![image](https://github.com/huawei-noah/trustworthyAI/assets/84905965/1c4d48cd-4072-44eb-9cf9-83628f23ae43)
This works. However I still have 2 questions: 
1. Set 0~7 all the cards, it only runs on card 0.
2. It seems that `gpu` can speed up compared to `cpu`, however it doesn't speed up much: `4.00s/it` vs `4.25s/it`.

**Comment by Ethan-Chen-plus** [comment]
Thanks a lot for your help!
