### ISSUE TITLE
PC's output? DAG or CPDAG?

### ISSUE THREAD

**Issue by AnOrdinaryDog** [huawei-noah/trustworthyAI#134]

**Comment by AnOrdinaryDog** [comment]
Sorry, I find that it can output a CPDAG... But which algorithm can handle the unobserved confoundings that can output a MAG?

**Comment by shaido987** [comment]
Hello,

the PC algorithm in gCastle will return a CPDAG (and can thus have undirected edges). For reference, you can take a look at the `orient` method inside the PC class and its return value:

https://github.com/huawei-noah/trustworthyAI/blob/feaf8f40920cd19ee6abc53a6d5448b2125564b3/gcastle/castle/algorithms/pc/pc.py#L158-L178

**Comment by AnOrdinaryDog** [comment]
> Hello,
> 
> the PC algorithm in gCastle will return a CPDAG (and can thus have undirected edges). For reference, you can take a look at the `orient` method inside the PC class and its return value:
> 
> https://github.com/huawei-noah/trustworthyAI/blob/feaf8f40920cd19ee6abc53a6d5448b2125564b3/gcastle/castle/algorithms/pc/pc.py#L158-L178

thanks～～
