### ISSUE TITLE
Tensors in different devices

### ISSUE THREAD

**Issue by cloudy-sfu** [huawei-noah/trustworthyAI#135]
There is a problem in `gcastle`. After debugging, I believe it is caused by pytorch, so I proposed an issue in pytorch repository.

https://github.com/pytorch/pytorch/issues/111573

I suggest `gcastle` to join and track this issue also, since the failure only occurs when I use `gcastle`. The reason is still unknown from my view.

**Comment by RishabhSamra** [comment]
I am also facing the similar issue while running the gradient-based algorithm on GPU. @huawei-noah-admin , @cloudy-sfu , any suggestions how we can rectify this issue of tensors on different device when I specify device_type= GPU and also device_ids =1 ?
