### ISSUE TITLE
Real-world dataset issues

### ISSUE THREAD

**Issue by AQingRoad** [huawei-noah/trustworthyAI#147]
There is no such data set, all warning types have real names, not a serial number. Or can you get cellular log data?

**Comment by shaido987** [comment]
Hello,

Which dataset are you trying to get and how are you loading it? You can download datasets from here: https://github.com/huawei-noah/trustworthyAI/tree/master/datasets

**Comment by AQingRoad** [comment]
"Thank you for your answer. I have a thesis topic on applying large language models to causal inference, but my attempts have shown that the causal relationships provided by large language models are poor. I wonder if incorporating real warning names like 'access overload' into large language models would make them better suited for this task. My question is: Is there any dataset with real warning names? From the real datasets mentioned in the link you provided, the warnings are just numbered like A_10, which I think is difficult for large language models to understand these warning codes."
感谢您的回答，我有一个毕设题目，是将大语言模型应用于因果推理，但是我尝试了一下，大语言模型给出的因果关系很差。我猜想如果能够将警告的真实名称如“访问过载”，应用到大语言模型中会不会更好的适应于大模型。我的疑问是：有没有这样带有真实警告名称的数据集。我看了您上述给的链接中的真实的数据集中，警告只是一个编号如A_10，我想大语言模型难以理解这个警告编号。

**Comment by AQingRoad** [comment]
> 你好
> 
> 您要获取哪个数据集以及如何加载它？您可以从以下位置下载数据集：https://github.com/huawei-noah/trustworthyAI/tree/master/datasets

**Comment by shaido987** [comment]
Hello,

Unfortunatly, we are not allowed to directly release the alarm names as the data is proprietary. Only the anonymized datasets have been approved for open-sourcing which is why the alarm names are encoded.
