### ISSUE TITLE
ImportError: cannot import name 'NotearsMLP' from 'castle.algorithms'

### ISSUE THREAD

**Issue by JERI1173** [huawei-noah/trustworthyAI#149]
I am using the latest version, cannot solve this error:
ImportError: cannot import name 'NotearsMLP' from 'castle.algorithms'

**Comment by shaido987** [comment]
Hello, 

NOTEARS-MLP is implemented under the name `NotearsNonlinear` with `model_type='mlp` (the default value). You can find the relevant code here:

https://github.com/huawei-noah/trustworthyAI/blob/22eb5a674b66e33a3ee3d00e7dac9d0a0ecd7bf3/gcastle/castle/algorithms/gradient/notears/torch/nonlinear.py#L42-L46

**Comment by shaido987** [comment]
You can use Notears-MLP as follows with the latest version of the package:

```python
from castle.algorithms import NotearsNonlinear

nt = NotearsNonlinear(model_type='mlp')
nt.learn(X)
```

There is actually no NotearsMLP class as the implementation is merged with Notears-SOB (hence the `model_type` argument) so you can't use `from castle.algorithms import NotearsMLP`. 

There is a small demo here that could be helpful:   
https://github.com/huawei-noah/trustworthyAI/blob/master/gcastle/example/notears/nonlinear_demo.py
