### ISSUE TITLE
running anm_demo.py gives module 'networkx' has no attribute 'to_numpy_matrix'

### ISSUE THREAD

**Issue by emoen** [huawei-noah/trustworthyAI#160]
Running the anm_demo.py crashes. It looks like to_numpy_matrix is deprecated for to_numpy_array in networkx but the requirement.txt isnt pinning down the version - with: networkx>=2.5

The error
```
simulator.py", line 168, in erdos_renyi
    B_und = DAG._graph_to_adjmat(G_und)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\local-packages\Python312\site-packages\castle\datasets\simulator.py", line 64, in _graph_to_adjmat
    return nx.to_numpy_matrix(G)
           ^^^^^^^^^^^^^^^^^^
AttributeError: module 'networkx' has no attribute 'to_numpy_matrix'

```

**Comment by shaido987** [comment]
Hi @emoen, if you install the latest version 1.0.4rc1 of gCastle this problem should be solved. This version is still a pre-release so it seems you need to set the version explicitly if you install with pip.

```
pip install gcastle==1.0.4rc1
```
