### ISSUE TITLE
算法

### ISSUE THREAD

**Issue by xyb151158** [huawei-noah/trustworthyAI#17]
请问CORL1和CORL2是什么算法，跟RL算法什么关系，在哪里可以看到详细介绍？

**Comment by kelizhang** [comment]
> 请问CORL1和CORL2是什么算法，跟RL算法什么关系，在哪里可以看到详细介绍？

请参考这篇工作：https://arxiv.org/abs/2105.06631

**Comment by xyb151158** [comment]
十分感谢，另外还有两个小问题：1）最终输出的causal_matrix中第i行第j列位置的元素为1代表一条从第i个变量到第j个变量的因果关系有向边，还是从第j个变量到第i个变量的有向边？2）算法中间过程的weighted_matrix中的权重值是代表对应因果关系边的强度或者说这条边存在的概率吗？

**Comment by kelizhang** [comment]
（1）在gCastle中，所有算法输出的causal_matrix中，第i行第j列为1代表一条从第i个变量到第j个变量的因果关系有向边。 （2）算法过程中应该是生成了一个序列，对应的是一个全图DAG，最后线性回归（如果是线性的话）得到weighted matrix，再根据大小过阈值得到0-1matrix，按我理解，对应的是你问题里面提到的边存在的概率，当然在边确认后这个概率也可作为因果强度.不知道回答了你的问题没有，或者可以再具体点吗？

**Comment by kelizhang** [comment]
> 十分感谢，另外还有两个小问题：1）最终输出的causal_matrix中第i行第j列位置的元素为1代表一条从第i个变量到第j个变量的因果关系有向边，还是从第j个变量到第i个变量的有向边？2）算法中间过程的weighted_matrix中的权重值是代表对应因果关系边的强度或者说这条边存在的概率吗？



> 十分感谢，另外还有两个小问题：1）最终输出的causal_matrix中第i行第j列位置的元素为1代表一条从第i个变量到第j个变量的因果关系有向边，还是从第j个变量到第i个变量的有向边？2）算法中间过程的weighted_matrix中的权重值是代表对应因果关系边的强度或者说这条边存在的概率吗？

（1）在gCastle中，所有算法输出的causal_matrix中，第i行第j列为1代表一条从第i个变量到第j个变量的因果关系有向边。 （2）算法过程中应该是生成了一个序列，对应的是一个全图DAG，最后线性回归（如果是线性的话）得到weighted matrix，再根据大小过阈值得到0-1matrix，按我理解，对应的是你问题里面提到的边存在的概率，当然在边确认后这个概率也可作为因果强度.不知道回答了你的问题没有，或者可以再具体点吗？

**Comment by kelizhang** [comment]
> 十分感谢，另外还有两个小问题：1）最终输出的causal_matrix中第i行第j列位置的元素为1代表一条从第i个变量到第j个变量的因果关系有向边，还是从第j个变量到第i个变量的有向边？2）算法中间过程的weighted_matrix中的权重值是代表对应因果关系边的强度或者说这条边存在的概率吗？

（1）在gCastle中，所有算法输出的causal_matrix中，第i行第j列为1代表一条从第i个变量到第j个变量的因果关系有向边。 （2）算法过程中应该是生成了一个序列，对应的是一个全图DAG，最后线性回归（如果是线性的话）得到weighted matrix，再根据大小过阈值得到0-1matrix，按我理解，对应的是你问题里面提到的边存在的概率，当然在边确认后这个概率也可作为因果强度.不知道回答了你的问题没有，或者可以再具体点吗？

**Comment by xyb151158** [comment]
> 
> 
> > 十分感谢，另外还有两个小问题：1）最终输出的causal_matrix中第i行第j列位置的元素为1代表一条从第i个变量到第j个变量的因果关系有向边，还是从第j个变量到第i个变量的有向边？2）算法中间过程的weighted_matrix中的权重值是代表对应因果关系边的强度或者说这条边存在的概率吗？
> 
> （1）在gCastle中，所有算法输出的causal_matrix中，第i行第j列为1代表一条从第i个变量到第j个变量的因果关系有向边。 （2）算法过程中应该是生成了一个序列，对应的是一个全图DAG，最后线性回归（如果是线性的话）得到weighted matrix，再根据大小过阈值得到0-1matrix，按我理解，对应的是你问题里面提到的边存在的概率，当然在边确认后这个概率也可作为因果强度.不知道回答了你的问题没有，或者可以再具体点吗？

十分感谢，也就是说两个变量间的权重是通过对这两个变量回归得到的，不知道是不是这个意思；另外，现在gCastle中有的这些算法是只能用于连续数据吗，还是离散数据，离散连续混合数据都可以，希望能够有一个清楚的说明。

**Comment by xyb151158** [comment]
还想问一下，连续数据在做因果关系发现causal discover之前，是否需要先对数据进行归一化，使其所有特征变量的值都在0-1之间？

**Comment by kelizhang** [comment]
gCastle中的目前大部分算法针对连续数据，在下一更新的版本中（7月底左右）将新增多个支持离散数据的CI测试算子，支持离散数据的ANM等
