### ISSUE TITLE
关于GAE中权值矩阵的初始化问题

### ISSUE THREAD

**Issue by ThinkNaive** [huawei-noah/trustworthyAI#21]
我理解关于权值矩阵初始化，应该是先做均匀分布随机，再将对角线归零，最后将得到的参数作为权值矩阵的初始化参数。因此我把[60-62行代码](https://github.com/huawei-noah/trustworthyAI/blob/master/Causal_Structure_Learning/GAE_Causal_Structure_Learning/src/models/gae.py#L60)：

    W = tf.Variable(tf.random.uniform([self.d, self.d], minval=-0.1, maxval=0.1,
                                      dtype=self.tf_float_type, seed=self.seed))
    self.W_prime = self._preprocess_graph(W)

改为：

    W = np.random.uniform(-0.1, 0.1, size=(self.d, self.d)) * (1 - np.eye(self.d))
    self.W_prime = tf.Variable(W)

但是得到的结果就很差，在第一轮iteration阶段，估计的图基本收敛在对角线处（见下图），而且最后得到的效果也很差，基本和NOTEARS和DAG-GNN类似甚至不如，请问这是什么原因呢？

![individualImage](https://user-images.githubusercontent.com/30410985/122764005-941f2900-d2d1-11eb-81f0-df45b49c6ba5.png)

附：这是原始代码在第一轮估计的图

![individualImage (1)](https://user-images.githubusercontent.com/30410985/122764234-dba5b500-d2d1-11eb-87f6-b41772039570.png)

希望能给我解答一下困惑，谢谢~

**Comment by kelizhang** [comment]
一个可能原因是，之前的实现里每次都会把对角线置0，现在修改后的代码只是初始化为0了，但是优化过程中对角线会尝试用自己预测自己（因为这样肯定是最准的），所以图会容易收敛到对角线

**Comment by ThinkNaive** [comment]
嗯，我明白了，非常感谢~
