### ISSUE TITLE
Cannot install with tensorflow-gpu >= 1.15.0

### ISSUE THREAD

**Issue by KMdsy** [huawei-noah/trustworthyAI#24]
gcastle is suggested to be installed using tensorflow>=1.15.0, which computing speed is very low, and the package cannot install with GPU version TensorFlow. When I install the gcastle using pip, it always installs a CPU version TensorFlow automatically. How can I fix it?

**Comment by kelizhang** [comment]
you could install the TensorFlow of GPU-version in advance，i.e.  before executing  'pip',   we will be fixing this bug soon, which is  because of the build file.
