### ISSUE TITLE
Error in loadNamespace(name) : there is no package called 'CAM'

### ISSUE THREAD

**Issue by HaiPhan1991** [huawei-noah/trustworthyAI#3]
Hi,
Thanks for great implementation. I have problem to with rpy2 packets. I got the error when running the code:
**rpy2.rinterface_lib.embedded.RRuntimeError: Error in loadNamespace(name) : there is no package called 'CAM'**

Do you have the same problem? I used rpy2 version 3.2.7 in ubuntu 16.0

**Comment by zhushy** [comment]
Just found that the CAM package was removed from cran (see https://cran.r-project.org/web/packages/CAM/index.html or below). The R codes for CAM can still be found in its archive, but I am not familar with R and don't know how to make it work. I will ask some friends. Or you may also do a search to see how to use R codes in this case. Thanks.
-----
Package ‘CAM’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2019-11-10 for policy violation.

Please use the canonical form https://CRAN.R-project.org/package=CAM to link to this page.

**Comment by zhushy** [comment]
> Hi,
> Thanks for great implementation. I have problem to with rpy2 packets. I got the error when running the code:
> **rpy2.rinterface_lib.embedded.RRuntimeError: Error in loadNamespace(name) : there is no package called 'CAM'**
> 
> Do you have the same problem? I used rpy2 version 3.2.7 in ubuntu 16.0

Sorry for a late reply. We have figured out how to install the CAM R package from local source. Please check the setup part and also let us know if it has any problem. Thanks!
