### ISSUE TITLE
Questions about CausalVAE

### ISSUE THREAD

**Issue by akdadewrwr** [huawei-noah/trustworthyAI#45]
In CausalVAE code 
Is there any special reason why using 4 different decoders? 

Besides, for `pendulum` and `flow` datasets, the latent space dimension should be equal to the dimension of the label, which is 4. Why the latent space dimension in code is set to be 16?  

I checked the Appendix of the paper: _we extend the multivariate Gaussian to the matrix Gaussian_. Why the model is designed in this way and what are the advantages if we set the VAE in this way? 

Many thanks for your response

**Comment by Sour1985** [comment]
https://github.com/niranjan94/show-java/releases/download/v3.0.5/ShowJava_v3_0_5.apk

**Comment by akdadewrwr** [comment]
Besides, Could the authors share the code for CelebA experiments?
If the code is shared by requirement, please share it to alexbeaton724@gmail.com
Thanks a lot!

**Comment by shaido987** [comment]
Hello, I have been in contact with one of the authors informing/reminding them of your questions here. There should hopefully be a reply soon.

**Comment by 26789564** [comment]
> Besides, Could the authors share the code for CelebA experiments? If the code is shared by request, please share it to [alexbeaton724@gmail.com](mailto:alexbeaton724@gmail.com) Thanks a lot!
The code of celeba experiment is only that the network structure is different from the original one, and the others are the same. Only the dataset needs to be modified

**Comment by akdadewrwr** [comment]
> 

thanks for your reply, but I am a little bit confused about the network structure.
In supplementary material, the model structure is:
![image](https://user-images.githubusercontent.com/98556303/156902824-e364da25-5179-4687-ba5e-9fd6f7b047f1.png)

Since the input shape is resized to (3x128x128), the output shape of the Encoder is (3x4x4). Should I flatten it first to shape (48,)? However, according to the supplementary material, the latent space size for CelebA model should be:
![image](https://user-images.githubusercontent.com/98556303/156903029-390a7655-5630-41c1-be1f-e2dea94bc485.png). Should I add a fc layer after the last encoder layer?

Besides, in mask.py, the ConvEncoder and ConvDecoder seem not correct too.

Only providing code for network structure will be very helpful since the CelebA dataset modification will be easy to implement.  
Thanks a lot

**Comment by shaido987** [comment]
Hello, sorry for the late reply. The first author of CausalVAE has already completed her internship with us. For a faster and more detailed reply, you can email this and any further questions to Mengyue Yang ([mengyue.yang.20@ucl.ac.uk](mailto:mengyue.yang.20@ucl.ac.uk)). You could include a link to this issue as context.
