### ISSUE TITLE
How to use my own datasets with these algorithms?

### ISSUE THREAD

**Issue by UzmaHasan** [huawei-noah/trustworthyAI#46]
I have a .CSV file of a dataset with ground truth being available. I want to see how these algorithms in the gCastle package perform on my dataset. My query is in the codes, where and how should I make changes so that the algorithms can read data from my own .CSV file.

**Comment by shaido987** [comment]
When working with the code and not the GUI, the easiest way would be to simply read the CSV files yourself and then call the algorithm you want to try. For example, using the notears algorithm:

```python
import pandas as pd
from castle.algorithms import Notears

df = pd.read_csv(...)
true_dag = pd.read_csv(...).values # should be a numpy array

# notears learn
nt = Notears()
nt.learn(X)

# plot est_dag and true_dag
GraphDAG(nt.causal_matrix, true_dag)

# calculate accuracy
met = MetricsDAG(nt.causal_matrix, true_dag)
print(met.metrics)
```

**Comment by UzmaHasan** [comment]
Thanks for the clarification and a quick response. It works fine this way. Great work!
