### ISSUE TITLE
No module named 'castle' after installed the gcastle == 1.0.3rc2

### ISSUE THREAD

**Issue by matthewmeng** [huawei-noah/trustworthyAI#48]
Hi I already installed gcastle with pip install gcastle==1.0.3rc2.
But when I try to run the demo program like anm_demo.py.
There still an error said 
`    from castle.common import GraphDAG
ModuleNotFoundError: No module named 'castle'`

Anyone know why there is a ModuleNotFoundError even I have installed the package already?

**Comment by matthewmeng** [comment]
Thanks, I've tried the `python -m pip gcastle==1.0.3rc2` but still didn't work.
will try the virtual env to see if it will work

**Comment by shaido987** [comment]
Make sure that the python you use to run the code is the same as the one you installed with. It's very easy to get confused if there are multiple versions. If you use something like PyCharm you should be able to install the package directly in the interpreter settings (or change which python interpreter is used to run with).

**Comment by matthewmeng** [comment]
> ple versions. If you use someth

it works now, thx mate
