### ISSUE TITLE
怎么使用web界面进行因果发现的可视化呢

### ISSUE THREAD

**Issue by Kinghup** [huawei-noah/trustworthyAI#52]
在论文中看到说还提供了web可视化的功能，叫castleboard，例子中没有说明怎么使用

**Comment by shaido987** [comment]
Thank you for the issue report. We will add some detailed instructions on how to run the GUI this week. For now, you can follow these steps:

1. download and unzip the source code.
2. make sure all packages in both `requirements.txt` and `requirements_web.txt` are installed.
3. create an empty 'data' folder under gcastle/web (currently missing, will be updated together with the instructions).
4. run the `main/py` file in the web directory. From the gcastle folder you can use: `python web/main.py`.
5. This will start a local flask server. To access the GUI, open a browser and go to the address printed in the output of step 4. This is the local IP address on port 5000 (e.g., 192.168.x.x:5000). Here, you need to add `index.html` for now so for the example IP address you need to access `192.168.x.x:5000/index.html`.

**Comment by sususnow** [comment]
可视化界面中的task，似乎不能使用。网页会提示“Failed to obtain the task list due to a network error. Refresh the page and try again.”  终端提示“sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: task”

**Comment by shaido987** [comment]
@sususnow It should be working correctly. It looks like the task.db file was not created for some reason. Make sure you have all the dependencies in both requirements.txt and requirements_web.txt installed. Also, you need to create an empty data folder from where you run the web/main.py file (so if you run from the web folder you need to create a data folder under there). The task.db file will be created in the data folder when you run main.py.

**Comment by sususnow** [comment]
@shaido987 我已安装requirements.txt和requirements_web.txt所需要的依赖，并且在web目录下建立空的data文件夹（因为我运行的是web目录下的main.py）。但在可视化界面新建Causal Discovery任务时，想使用buit-in database，却显示no data。通过代码查看task.db，显示的是”nothing to show"。请问该如何排查错误，可以使用内置数据库呢？

**Comment by shaido987** [comment]
@sususnow I see. The built-in dataset option is meant to use one of the previously generated datasets. So you need to first create a dataset generation task to create a synthetic dataset. When that is done, then you can select this dataset in the causal discovery task.
