### ISSUE TITLE
[Feature request]: Adding GES algorithm to the package

### ISSUE THREAD

**Issue by AlxndrMlk** [huawei-noah/trustworthyAI#56]
Hi, 

I think it would be great to add GES algorithm implementation to `gcastle`. It would make broad comparisons between algorithms easier.

There is an existing Python implementation of GES by Juan Gamella: https://github.com/juangamella/ges

Maybe it could be integrated into `gcastle`. What are your thoughts? 

If you think it's a good idea, I am happy to help with the integration.

BTW., I'll be speaking about `gcastle` in my upcoming conference talk next week: https://ghostday.pl/#agenda

**Comment by shaido987** [comment]
Hello,

Yes, the GES algorithm is something that has been on the todo list for some time.  In truth, we already have a colleague that recently started working on an implementation to add to gcastle. It should be released in the near future although I'm not sure regarding the exact timeframe.  

Also, thanks for contributing to the exposure of the package, that's very exciting to hear. :)

**Comment by AlxndrMlk** [comment]
Hi @shaido987,

great to hear that GES is in the pipeline! 

> Also, thanks for contributing to the exposure of the package, that's very exciting to hear. :)

My pleasure. It's a great, very useful and much needed package. 

Another event where I'll talk about `gcastle` is PyData Hamburg: https://t.co/YgcD6Ka9lR

**Comment by shaido987** [comment]
Hi @AlxndrMlk,

The GES algorithm has been added in the latest version of gcastle (1.0.3). It took a bit longer than initially estimated but now it's available.

**Comment by AlxndrMlk** [comment]
That's great news, @shaido987! Thank you for the update!
