### ISSUE TITLE
HPCI Implementation

### ISSUE THREAD

**Issue by gwinch97** [huawei-noah/trustworthyAI#57]
Hi,

First of all, thank you for all your work on this package, collecting together the distributed (and sometimes un-implemented) research on causal inference is infinitely helpful and useful.

I was just wondering if you had any rough ETA on the implementation of the HPC algorithm within your toolbox? The results of this paper look extremely promising and I would like to test them further.

Many thanks

**Comment by AlxndrMlk** [comment]
Hi @gwinch97,

can your share the HPC paper you mentioned?

**Comment by gwinch97** [comment]
Hi @AlxndrMlk 

Apologies for the confusion, I meant HPCI (hybrid causal graph learning method - [https://arxiv.org/pdf/2105.03092.pdf](https://arxiv.org/pdf/2105.03092.pdf)). The only reason I asked here directly is that on the gCastle readme I see it as under development on the algorithms table which was exciting!

**Comment by shaido987** [comment]
Hello,

Yes, we plan to add the HPCI algorithm to the toolbox in the near future. Although I can't give a definite date, we hope that it can be added in the next larger update (together with the GES algorithm). The current plan for this release is within 1-2 months.

**Comment by gwinch97** [comment]
Many thanks, I look forward to it!
