### ISSUE TITLE
关于测试

### ISSUE THREAD

**Issue by KiritoZhang** [huawei-noah/trustworthyAI#6]
您好！感谢您在ICLR2020发表的论文中提出的方法。
我有四个问题想请问一下，在节点数一定的情况下。
1. 该模型若仅使用一种DAG图创建的数据集进行训练后，表现良好。当使用基于另一种DAG图创建的数据集进行测试，是否就无法发现数据间的因果关系？
2. 若使用多种DAG关系图的综合数据集对模型进行训练，模型能否发现因果关系？
3. 假设模型能训练好并发现，当使用训练集以外的DAG图的数据进行测试，是否无法发现因果关系？
4. 用创建的综合数据集训练的模型，若换成真实数据集，是不是不能发现因果关系。

**Comment by zhushy** [comment]
你好，我试着回答下你的问题啊：本身来说算法是根据一个因果图+对应的数据来做的，所以如果换了一批数据，就是重新训练了下。
1. 并不是啊，从算法来说应该是都可以做的。当然有些图结构本身就会难些，例如sf的图可能会比er的图难。
2. 我们这里（可能绝大多数的工作也是这样的）只假设一个DAG+对应的观测数据。一般来说，DAG也就是因果关系是一致的，但是具体的影响（例如函数可以是不同的），这种倒是有一些工作来处理的。
3. 应该还是可以的。
4. 有一些实际数据的例子，主要来说要大概清楚实际数据的产生机理，然后修改算法适配，结果应该还是不错的。

**Comment by KiritoZhang** [comment]
好的，明白了。
感谢你的回答。
