### ISSUE TITLE
How to combine Causal discovery and RL

### ISSUE THREAD

**Issue by MAX00008888** [huawei-noah/trustworthyAI#60]
Hi, thank you so much for this amazing work.
I don't understand how to combine RL algorithm and Causal discovert algorithm., and how to use the BIC score.
Could you please help me with it.

Thank you so much!

**Comment by MAX00008888** [comment]
I refer to your papers, and then I want to try to modify the reinforcement learning algorithm so that it can make causal discovery.
I modified the TD3 algorithm in d3rlpy open source library, modified the computee _ critical _ loss part of ddpg_impl module, added the algorithm of causal discovery in this part, predicted the directed graph according to the data, then scored the graph with BIC scoring function, and used the returned value as rewards, but the value of rewards was too large, resulting in the calculated critic loss value being too large. Please think about how to correctly use BIC score in causal reinforcement learning.

**Comment by zhushyu** [comment]
sorry, just notice this issue. you mean BIC score is too large? in this case, you may divide BIC score by the sample number, or do some normalization as you can know a range for the BIC score according to the true graph.
