### ISSUE TITLE
Discrete-Valued Variables?

### ISSUE THREAD

**Issue by chihyuanchiu** [huawei-noah/trustworthyAI#63]
Hi - Do the algorithms in this repository work with discrete-valued variables, e.g., categorical variables? Thanks.

**Comment by shaido987** [comment]
Hello,

the majority of the implemented algorithms works on continuous data. One exception being the PC algorithm where the conditional independence test can be changed to work with entirely discrete datasets.

**Comment by chihyuanchiu** [comment]
Hi - Got it; thanks a lot.

**Comment by shaido987** [comment]
You're welcome.
