### ISSUE TITLE
why not be a matrix for MIC&TIC

### ISSUE THREAD

**Issue by samuelzhoudev** [huawei-noah/trustworthyAI#64]
In the CasualVAE, the MIC and TIC should be a matrix between learned representation z and the label u , how to get a single scalar ?

**Comment by zhushyu** [comment]
Hi, the first author has finished her internship with us. For a quick reply (without forwarding this issue to her by us), can you directly email the question to Mengyue Yang ([mengyue.yang.20@ucl.ac.uk](mailto:mengyue.yang.20@ucl.ac.uk)) ? 

Best Regards.

**Comment by shaido987** [comment]
Regarding the confusion of MIC and TIC, these are single value metrics used for evaluation. 

MIC is the maximal information coefficient and TIC is the total information coefficient. MIC considers the normalized maximal mutual information value of different combinations of bin counts n_X and n_Y. This will return a matrix with values in [0,1] (which could be the reason for the confusion). MIC corresponds to the largest value in this matrix while TIC instead considers the sum of values (both are thus single values).

For more detailed information for the implementation in the paper, etc., please contact the first author as indicated by @zhushyu.

References to read more:
For MIC: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3325791/#S1title
For MIC and TIC: http://web.mit.edu/dnreshef/www/websiteFiles/Papers/AOAS-2018.pdf
You can also see this blogpost with some easy explanation with further reference papers and links to python and R code: https://medium.com/@rhondenewint93/on-maximal-information-coefficient-a-modern-approach-for-finding-associations-in-large-data-sets-ba8c36ebb96b

**Comment by samuelzhoudev** [comment]
> Regarding the confusion of MIC and TIC, these are single value metrics used for evaluation.
> 
> MIC is the maximal information coefficient and TIC is the total information coefficient. MIC considers the normalized maximal mutual information value of different combinations of bin counts n_X and n_Y. This will return a matrix with values in [0,1] (which could be the reason for the confusion). MIC corresponds to the largest value in this matrix while TIC instead considers the sum of values (both are thus single values).
> 
> For more detailed information for the implementation in the paper, etc., please contact the first author as indicated by @zhushyu.
> 
> References to read more: For MIC: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3325791/#S1title For MIC and TIC: http://web.mit.edu/dnreshef/www/websiteFiles/Papers/AOAS-2018.pdf You can also see this blogpost with some easy explanation with further reference papers and links to python and R code: https://medium.com/@rhondenewint93/on-maximal-information-coefficient-a-modern-approach-for-finding-associations-in-large-data-sets-ba8c36ebb96b

If z and u are one-dimensional, just as you said; but when it muti-dimensional, every dimensional z get the scalar with the different u, so that be a matrix;  you can see the  example like this:
![image](https://user-images.githubusercontent.com/43336428/165434958-4bc16f88-852f-413f-97cb-130c60ad787f.png)
 
The link in : 
https://minepy.readthedocs.io/en/latest/python.html

looking forward your reply

**Comment by shaido987** [comment]
Each z is associated with a single u since a single image will give one representation vector z and has a single ground truth concept vector u. The dimensions of z and u are the same (n) so it's possible to compute n MIC/TIC values (one for each concept). This is equivalent to the diagonal in the matrix. We can then average over the results from each concept (as noted in the paper in the caption of Table 1, the MIC and TIC values are averages).

Please note that the above is just my assumption and I was not involved in the CausalVAE work, so it would be better to contact the first author to confirm.

**Comment by samuelzhoudev** [comment]
> Each z is associated with a single u since a single image will give one representation vector z and has a single ground truth concept vector u. The dimensions of z and u are the same (n) so it's possible to compute n MIC/TIC values (one for each concept). This is equivalent to the diagonal in the matrix. We can then average over the results from each concept (as noted in the paper in the caption of Table 1, the MIC and TIC values are averages).
> 
> Please note that the above is just my assumption and I was not involved in the CausalVAE work, so it would be better to contact the first author to confirm.

yep, I just think so,thank you for your reply.  I'll check with the first author.
