### ISSUE TITLE
Error with GAE

### ISSUE THREAD

**Issue by manmeet3591** [huawei-noah/trustworthyAI#66]
I am trying to use GAE following https://github.com/huawei-noah/trustworthyAI/blob/master/gcastle/example/gae/gae_demo.py and am getting the following error

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_33/894238180.py in <module>
      2 from castle.metrics import MetricsDAG
      3 from castle.datasets import DAG, IIDSimulation
----> 4 from castle.algorithms import GAE
      5 
      6 

ImportError: cannot import name 'GAE' from 'castle.algorithms' (/opt/conda/lib/python3.7/site-packages/castle/algorithms/__init__.py)

**Comment by shaido987** [comment]
The code for the GAE algorithm is being refactored and is not directly available in the current newest version of the library (1.0.3rc2). The code uses tensorflow and we are moving away from that to only using pytroch and mindspore. For now, to use the GAE algorithm you can either downgrade to use gcastle 1.0.3rc1 or change the import statement to use:

```python
from castle.algorithms.gradient.gae.tensorflow.gae import GAE
```

Note that this requires tensorflow installed (tested with version 1.15.0).

**Comment by manmeet3591** [comment]
Thank you!
