### ISSUE TITLE
Questions about CausalVAE

### ISSUE THREAD

**Issue by CCCx-sc** [huawei-noah/trustworthyAI#70]
The picture I generated when running the run_flow is like this,What can I do to generate the correct picture? I haven't modified any code.
![HR3OTJ8%B7T0X1B56)W47V5](https://user-images.githubusercontent.com/83278923/178144022-a9e85cdc-6d23-4de9-bb46-49f70e680823.png)

.

**Comment by CCCx-sc** [comment]
> 我运行run_flow的时候生成的图片是这样的，要怎么做才能生成正确的图片呢？我没有修改任何代码。 ![HR3OTJ8%B7T0X1B56)W47V5](https://user-images.githubusercontent.com/83278923/178144022-a9e85cdc-6d23-4de9-bb46-49f70e680823.png)
> 
> .

**Comment by Ber666** [comment]
We have the same issues running both datasets. May I ask how did you solve this issue?
