### ISSUE TITLE
[Enhancement] Add whitelist and blacklist in PC algorithm 

### ISSUE THREAD

**Issue by marvher** [huawei-noah/trustworthyAI#72]
Dear huawei team,

I have recognized that several implementations of the PC algorithm allow providing "arcs" which are allowed/known (=whitelist) or not allowed (=blacklist), e.g. https://www.bnlearn.com/documentation/man/constraint.html.
This also accelerate the computation.

Maybe, you can also add these your PC algorithms :)

Best regards,
Marvin

**Comment by shaido987** [comment]
Hello,

This would be a very nice enhancement to the current PC algorithms. 
We have had some plans to introduce prior knowledge to all algorithms, however there has not been time to start this larger project (it's not of very high priority right now).

In the meantime, if you want to take a shot at trying to implement it for the PC algorithms that is very welcome.

**Comment by shaido987** [comment]
We have added prior knowledge to the PC algorithm in version 1.0.3 of gcastle (see #73).  You can see the PC demo code for a usage example: https://github.com/huawei-noah/trustworthyAI/blob/master/gcastle/example/pc/pc_demo.py.
