### ISSUE TITLE
Kernel-based Test for PC

### ISSUE THREAD

**Issue by lmz123321** [huawei-noah/trustworthyAI#75]
Hi, I notice some kernel-based conditional independence test methods, e.g., hsci, is implemeneted in the CITest folder.
However, for Parallel-PC algorithm, only fisherz, chi2, g2 tests are avariable.
Is it possible to modify the code and use these kernel-based tests instead?

**Comment by shaido987** [comment]
Hello, 

From the newest version of the gCastle package (1.0.3), it is possible to use any conditional independence test implemented under the [CITest class](https://github.com/huawei-noah/trustworthyAI/blob/2e08a7aab82e7ea6ba340ecbfccb427b67e3be3f/gcastle/castle/common/independence_tests.py#L23) in the PC algorithms. So in addition to fisherz, chi2, and g2, it is possible to use freeman_tukey, modify_log_likelihood, neyman, cressie_read by using the corresponding function as an input argument to PC (strings are not supported for these). For example:

```python
from castle.common.independence_tests import CITest

pc = PC(variant='original', ci_test=CITest.freeman_tukey)
```

Unfortunately, HSCI is not one of these methods as its current implementation has different input parameters (see the code [here](https://github.com/huawei-noah/trustworthyAI/blob/2e08a7aab82e7ea6ba340ecbfccb427b67e3be3f/gcastle/castle/common/independence_tests.py#L550)). For now, you could try adjusting the input arguments to match those of the CITest methods. You then can use it in PC as shown in the code example above.

**Comment by lmz123321** [comment]
Thanks a lot for your help.
