### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tensoflow==1.13.1 ERROR: No matching distribution found for tensoflow==1.13.1 , When i am using pip install -r requirement.txt, it give me this error, I am using python==3.7

### ISSUE THREAD

**Issue by vickykhan89** [huawei-noah/trustworthyAI#8]

**Comment by vickykhan89** [comment]
I need your suggestions about this, the requirements.text file inside Causal structure learning folder. looking forward for your response

**Comment by zhushy** [comment]
> I need your suggestions about this, the requirements.text file inside Causal structure learning folder. looking forward for your response

Hi, thanks for reaching out. You may install Tensorflow by specifying its version, and the available versions can be found by checking the source address. We used 1.13.x to avoid conflict of the logger part of Tensorflow with ours. The codes work fine using Tensorflow 1.15 as we tested, but may not output all the logging information.

**Comment by vickykhan89** [comment]
@zhushy Hi Respected, Thank you for your nice response. I follow your suggestions, and I installed tensorflow==1.15 successfull with other dependencies, but when i run the setup_CAM.py I got the following error "raise ValueError('The system "%s" is not supported.')
ValueError: The system "%s" is not supported.", I search around but could not find solution, could you please give me advice for this. Will be thankful and looking forward to you.

**Comment by zhushy** [comment]
Weird. Have you installed the r2py package?  how about copying the codes and running the codes directly?
