### ISSUE TITLE
Inconsistency between Examples and Output in adding priori_knowledge

### ISSUE THREAD

**Issue by xwbxxx** [huawei-noah/trustworthyAI#80]
![image](https://user-images.githubusercontent.com/49603007/193059485-6cb2cb08-4329-4789-970e-2387fbbea89c.png)

Based on the output and comments of the example in the screenshot above (See [priori_knowledge.py #line 45](https://github.com/huawei-noah/trustworthyAI/blob/master/gcastle/castle/common/priori_knowledge.py#L45) and [priori_knowledge.py #line 69](https://github.com/huawei-noah/trustworthyAI/blob/master/gcastle/castle/common/priori_knowledge.py#L69)), you may want  to add **Directed Edge** '0-->1' and '1-->2' after this code:
 > \>\>\>p.add_required_edges([(0, 1), (1, 2)]

which can be expressed as adjacency matrix:
> p.matrix[0][1] = 1;
> p.matrix[1][0] = 0;
> p.matrix[1][2] = 1;
> p.matrix[2][1] = 0 ;

The function has only 2 lines：
![image](https://user-images.githubusercontent.com/49603007/193064085-bd2a0f83-d8fa-4043-be46-5594b0ecc1a3.png)

 However, it seems that you've forgotten set the **_0_**, but only the _**1**_, so actually, the output is:
> p.matrix[0][1] = 1;
> p.matrix[1][0] = -1;
> p.matrix[1][2] = 1;
> p.matrix[2][1] = -1 ;

I am not sure if I have misunderstood but this error can lead to serious problems, providing incorrect priori knowledge when orienting.

**Comment by shaido987** [comment]
Hello, thanks for your question.

Here, -1 corresponds to no knowledge of a given edge. In the case of 
```
p.add_required_edges([(0, 1), (1, 2)]
```
we do not make any assumptions if there are edges going from 1 -> 0 or 2 -> 1. Both [1][0] and [2][1] are therefore kept as -1. If there exists prior knowledge that the edge is in fact directional and there is no possibility of it being undirected then 1 -> 0 and 2 -> 1 can be added to the forbidden edges using `add_forbidden_edges` which will set these elements in the matrix to 0.

We are trying to keep the API as general as possible and want to allow prior knowledge where one direction is known and the opposite direction is unknown.

**Comment by xwbxxx** [comment]
> Hello, thanks for your question.
> 
> Here, -1 corresponds to no knowledge of a given edge. In the case of
> 
> ```
> p.add_required_edges([(0, 1), (1, 2)]
> ```
> 
> we do not make any assumptions if there are edges going from 1 -> 0 or 2 -> 1. Both [1][0] and [2][1] are therefore kept as -1. If there exists prior knowledge that the edge is in fact directional and there is no possibility of it being undirected then 1 -> 0 and 2 -> 1 can be added to the forbidden edges using `add_forbidden_edges` which will set these elements in the matrix to 0.
> 
> We are trying to keep the API as general as possible and want to allow prior knowledge where one direction is known and the opposite direction is unknown.

Thank you for the reply, I think the examples mislead me, We'll be appreciated it if the demo could be updated.

**Comment by shaido987** [comment]
@xwbxxx : Yes, you are entirely correct. This should be fixed with the merged PR.
