### ISSUE TITLE
A question about TTPM code

### ISSUE THREAD

**Issue by oyxy2019** [huawei-noah/trustworthyAI#86]
hello, Congratulations on your great work!

I want to figure out why:
In your paper, Formula (8), 

![PRTMCXP$9C@QEM9TRW79R3F](https://user-images.githubusercontent.com/53966815/212827887-4b016b6c-8c10-4de0-acbf-ffdce10f2799.png)
- "κ(t) characterize the time-decay of the causal inﬂuence with the hyper-parameter δ"
- t′ < t  (I think t' is the timestamp before t )

but in your code, line166, it used "self._max_s_t" (which means the max value of timestamp) rather than the timestamp of event v

https://github.com/huawei-noah/trustworthyAI/blob/5de644207aa327cdd42eb04e8a041518544302c0/gcastle/castle/algorithms/ttpm/ttpm.py#L157-L168

Looking forward to your reply!

**Comment by shaido987** [comment]
Hello, 

Thank you for the question! In my understanding of the code, `self._decay_effects` is only used by the EM algorithm when updating the parameters (see Eq 11 in the paper). For the lambda_v in Eq 8, it should actually be represented by `self._effect_tensor_decays`. The computation of `self._effect_tensor_decays` is done in these lines:

https://github.com/huawei-noah/trustworthyAI/blob/5de644207aa327cdd42eb04e8a041518544302c0/gcastle/castle/algorithms/ttpm/ttpm.py#L245-L296

**Comment by oyxy2019** [comment]
Thank you! 
I used to confuse `self._decay_effects` and `self._effect_tensor_decays`. 
Your answer is really helpful to me.😀
