### ISSUE TITLE
Bug: gae.py, matrices on different devices

### ISSUE THREAD

**Issue by Howardhuang98** [huawei-noah/trustworthyAI#88]
When I specify the device type = 'gpu' and run the gae. 

`
ga = GAE(input_dim=1, hidden_dim=128, device_type="gpu", epochs=2)
ga.learn(x)
`
Error: 
`
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat1 in method wrapper_addmm)
`

I fixed it by modifying `gae.py`, line 160: `x = torch.from_numpy(data)` to `x = torch.from_numpy(data).to(self.device)`

**Comment by shaido987** [comment]
Hello, 

Thank you for the bug report and for taking the time to localize the issue! We will include your fix in the next version of the package.
