### ISSUE TITLE
In `IIDSimulation` what does `mim` stand for?

### ISSUE THREAD

**Issue by AlxndrMlk** [huawei-noah/trustworthyAI#89]
Hi,

In the `datasets` module we can specify different SEM types when using `IIDSimulation` object.

What does non-linear option `mim` stand for?

**Comment by shaido987** [comment]
Hello,

It stands for "multiple index model". You can take a look at the NOTEARS follow-up paper ([Learning sparse nonparametric DAGs](https://arxiv.org/abs/1909.13189)) which uses the same non-linear options. They have some more details about the options in the B section in the appendix (see the index model instance).

**Comment by AlxndrMlk** [comment]
Thank you for a quick reply and links to the resources @shaido987
