### ISSUE TITLE
can causalvae reproduce?

### ISSUE THREAD

**Issue by TristanMeng** [huawei-noah/trustworthyAI#91]
I won't reproduce the do calculation。 can someone do it?

**Comment by TristanMeng** [comment]
the causalvae paper

**Comment by shaido987** [comment]
Hello, the first author of CausalVAE has completed her internship with us. For a faster and more detailed reply, you can email your questions to Mengyue Yang ([mengyue.yang.20@ucl.ac.uk](mailto:mengyue.yang.20@ucl.ac.uk)).
