### ISSUE TITLE
docker not working with suggested docker pull 

### ISSUE THREAD

**Issue by margasm99** [huawei-noah/trustworthyAI#92]
I am able to pull the image by using "docker pull gcastle/castleboard-cpu-torch:1.0.1.211112.beta" however when I try t run the container I get the error "ModuleNotFoundError: No module named 'colorama'" and it seems as what is available is not up to date since for example the logger.py does not exist. My question is how do I run this so I can use the GUI shown in the video provided with the paper.

**Comment by shaido987** [comment]
Hello, gcastle does not use or even reference `colorama` anywhere in the source code so I'm not entirely sure how you can get this error. I think it should be unrelated to the usage of gcastle.

For the GUI, if you can't get the docker to work then you can always follow the steps outlined here:
https://github.com/huawei-noah/trustworthyAI/blob/master/gcastle/web/README.md

**Comment by margasm99** [comment]
Thank you!
