### ISSUE TITLE
Improve `castle` dependency robustness against different `networkx` versions

### ISSUE THREAD

**Issue by AlxndrMlk** [huawei-noah/trustworthyAI#94]
Hi,

While running comparative experiments between various causal discovery methods implemented in `castle` and other packages, I noticed one common dependency issue.

`castle` uses `networkx`'s method `nx.from_numpy_matrix(.)`

This method is not supported in newer versions of `networkx` (> 2.8)

It seems that `nx.from_numpy_matrix(.)` is used in 3 or 4 places in the entire `castle` codebase. 

Up to my best knowledge, the following changes could make `castle` compatible with versions 2.8 and 3.+

* `nx.from_numpy_matrix(G, create_using=nx.DiGraph)` can be replaced with `nx.DiGraph(G)` 
* `nx.from_numpy_matrix(G, create_using=nx.Graph)` can be replaced with `nx.Graph(G)`

What are your thoughts on this?

Best,
Alex

**Comment by shaido987** [comment]
Hi Alex,

Yes, this is a problem with newer networkx versions. It has also been raised in issue #87.  
The change to directly use `nx.DiGraph(G)` and `nx.Graph(G)` looks very elegant and should work correctly as the input is always a numpy array. If you have time, you are more than welcome to add a PR with this change and I will merge it.
