### ISSUE TITLE
GES not implemented to test in the GUI 

### ISSUE THREAD

**Issue by margasm99** [huawei-noah/trustworthyAI#96]
Is the GES algorithm not implemented to use in the GUI? When I select the algorithm I want to use GES is not an option, how should I test it?

**Comment by shaido987** [comment]
Hello, thanks for your bug report.

This should be fixed with the change added in #98. You can try to download the latest version of the code and it should be possible to use GES in the web GUI.

**Comment by shaido987** [comment]
I've confirmed the code and it should be correct. I think it's due to you having an installation of gcastle with the older code (e.g. installed using pip). You can try to uninstall it first and then try running the web GUI again. This should be fixed later when the version is updated.

**Comment by margasm99** [comment]
Thank you that worked!
